---
title: "fftrack_code.Rmd"
author: "Leeya Pressburger"
date: "2/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup
Load in necessary packages, read in an ini file and initiate core, and set seed for reproducibility.

```{r intro}
library(hector)
library(dplyr)
library(ggplot2)

# Read in ini file, initiate new core
# Will need to change to SSP
rcp45 <- system.file("input/hector_rcp45.ini", package = "hector") 
core <- newcore(rcp45)

# Random number generator to allow for reproducibility 
set.seed(10)

```

## Create dataset
```{r params}
# Create runlist of parameters of interest
runlist <- tibble(
  run_number = 1:1000,
  "BETA" = rnorm(1000, mean = 0.36, sd = 0.036),
  "Q10_RH" = rlnorm(1000, meanlog = log(2.0), sdlog = 0.2),
  "ECS" = rlnorm(1000, meanlog = log(3.0), sdlog = 0.3)
)

# Name and units of parameters
name_vector <- c("BETA" = BETA(), "Q10_RH" = Q10_RH(), "ECS" = ECS())
units_vector <- c("BETA" = "(unitless)", "Q10_RH" = "(unitless)", "ECS" = "degC")
```

## Define function and run loop
```{r functions}
run_hector <- function(pdata, c) {
  for(p in colnames(pdata)) {
    message("Setting ", p)
    setvar(c, NA, do.call(p, list()), pdata[p][[1]], units_vector[p])
  }
  setvar(c, NA, TRACKING_DATE(), 1750, NA)
  reset(c)
  run(c)
  tdata <- get_tracking_data(c)
  tdata %>% filter(year %in% c(2100:2200))
  
}

# Run function for each row of the runlist
output <- list()
output_1000 <- list()

system.time({
  for(row in seq_len(nrow(runlist))) {
    output_1000[[runlist$run_number[row]]] <- run_hector(runlist[row,][-1], core)
  }  
})

```

## Process data
``` {r data}
# Get output dataframe
output <- bind_rows(output, .id = "run_number")
output_1000 <- bind_rows(output_1000, .id = "run_number")

# Can left join with runlist to get param values
# Make sure data is same class
output$run_number <- as.integer(output$run_number)
output <- left_join(output, runlist)

output_1000$run_number <- as.integer(output_1000$run_number)
output_1000 <- left_join(output_1000, runlist)

# Max lines display
# If there are over 100 observations per time point, we want to use 
# slice_sample() to randomly select rows to plot.
# We want to create a check that accomplishes this.


# Note to self - make sure output dataframe is correctly referenced here
# This is what will go in the ggplot call
max_display <- if(length(unique(output_1000$run_number)) > 101) slice_sample(output_1000, n = 100)

```

## Data visualization!

``` {r graphs_pt1}
# This code just looks at the atmosphere pool
atmos <- output %>%
  filter(pool_name == "atmos_c")

# This plot looks at source fraction by source pool in the atmosphere as well as the median run.

ggplot(atmos, aes(year, source_fraction, color = as.factor(run_number), group = run_number)) +
  geom_line(size = 0.5, show.legend = FALSE) +
  facet_wrap(~source_name, scales = "free") +
  labs(x = "Year",
       y = "Source fraction",
       title = "Atmosphere pool - source fraction by pool") +
  scale_color_grey(start = 0.7, end = 0.7) +
  stat_summary(color = "black",
               fun = median, 
               geom = "line", 
               group = "run_number",
               size = 0.7) +
  theme_light()

# Compute coefficient of variability
atmos2100 <- atmos %>%
  filter(year == "2100") %>%
  group_by(source_name) %>%
  mutate(sdev = sd(source_fraction)) %>%
  mutate(mean = mean(source_fraction)) %>%
  mutate(cv = sdev / mean)

### How to plot?
ggplot(atmos2100, aes(source_fraction, cv, group = source_name, color = source_name)) +
  geom_point() +
  labs(x = "Source fraction",
       y = "CV",
       title = "atmos_c pool") +
  theme_light()

```

``` {r graphs_pt2}
# This chunk looks at the atmosphere pool with just one source (soil) and plots source fraction over time with a mean and confidence interval

soil <- atmos %>% 
  filter(source_name == "soil_c") %>%
  group_by(year) %>%
  summarize(sf_sd = sd(source_fraction), 
            sf_min = min(source_fraction),
            sf_max = max(source_fraction),
            sf_median = median(source_fraction))

ggplot(soil, aes(year)) +
  geom_line(aes(y = sf_median)) +
  geom_ribbon(aes(ymin = sf_min, ymax = sf_max), alpha = 0.2) +
  geom_ribbon(aes(ymin = sf_median - sf_sd, ymax = sf_median + sf_sd), alpha = 0.2) +
  labs(x = "Year",
       y = "Source fraction",
       title = "atmos_c pool, soil_c source")
```

```{r graphs_pt3}
# Part 3
# Single time point, pool, and source - how is the parameter space linked to output?

single <- output_1000 %>%
  filter(pool_name == "atmos_c") %>%
  filter(source_name == "soil_c") %>%
  filter(year == 2100)

ggplot(single, aes(BETA, Q10_RH, color = source_fraction)) +
  geom_point() +
  scale_color_viridis_c() +
  labs(x = "beta",
       y = "Q10",
       title = "Parameter relationship (n = 1000)")

ggplot(single, aes(BETA, ECS, color = source_fraction)) +
  geom_point() +
  scale_color_viridis_c() +
  labs(x = "beta",
       y = "ECS",
       title = "Parameter relationship (n = 1000)")

ggplot(single, aes(ECS, Q10_RH, color = source_fraction)) +
  geom_point() +
  scale_color_viridis_c() +
  labs(x = "ECS",
       y = "Q10",
       title = "Parameter relationship (n = 1000)")


# Trying contours
single %>% ggplot(aes(BETA, Q10_RH, source_fraction)) +
  geom_contour() 
```