---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

Step one: Read in table of parameters, beta and q10  
The table contains median values for both parameters as specified in the RCP 4.5 ini file as well as sigma values. Sigma values range from +- 1% to 5% of the median. There are ten observations for each parameter

``` {r setup}
param_table <- read.csv("params.csv")
```

## Hector

```{r hector}
library(hector)
library(dplyr)

rcp45 <- file.path("C:\\Users\\pres520\\Documents\\GitHub\\hector\\inst\\input\\hector_rcp45.ini")

# We need to set beta and q10 equal to the values from our table - we want to know what happens when they are varied

# Create table
values <- as.data.frame(sort(rnorm(10, mean = 0.36, sd = 0.036)))
colnames(values) <- "beta"
values$Q10 <- sort(rnorm(10, mean = 2.0, sd = 0.2))

set_beta <- function(data){
  core <- newcore(rcp45)
  setvar(core, NA, BETA(), data, NA)
  setvar(core, NA, TRACKING_DATE(), 1750, "(unitless)")
  run(core)
  tdata <- get_tracking_data(core)
  tdata$beta <- data
  tdata
}

beta_output <- lapply(values$beta, set_beta) %>% bind_rows()

set_q10 <- function(data){
  core <- newcore(rcp45)
  setvar(core, NA, Q10_RH(), data, NA)
  setvar(core, NA, TRACKING_DATE(), 1750, "(unitless)")
  run(core)
  tdata <- get_tracking_data(core)
  tdata$q10 <- data
  tdata
}

q10_output <- lapply(values$Q10, set_q10) %>% bind_rows()

```
